// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-iKylDXsSSisH18qJh0dqIACZGjRX3k',
    appId: '1:891973890751:web:0c5662d38c82916ce10c0a',
    messagingSenderId: '891973890751',
    projectId: 'ploff-kebab-2717e',
    authDomain: 'ploff-kebab-2717e.firebaseapp.com',
    storageBucket: 'ploff-kebab-2717e.appspot.com',
    measurementId: 'G-SWGLJTMW9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlUEUP7OAyPXeDb7fXE4yXkxnb_nKKs0A',
    appId: '1:891973890751:android:94d14da9e28bf63ae10c0a',
    messagingSenderId: '891973890751',
    projectId: 'ploff-kebab-2717e',
    storageBucket: 'ploff-kebab-2717e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvX_BWc4islUgPY48mPvMjqUcLNBGRyZg',
    appId: '1:891973890751:ios:f533ddd9f4a2b6eae10c0a',
    messagingSenderId: '891973890751',
    projectId: 'ploff-kebab-2717e',
    storageBucket: 'ploff-kebab-2717e.appspot.com',
    iosBundleId: 'com.example.ploffKebab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvX_BWc4islUgPY48mPvMjqUcLNBGRyZg',
    appId: '1:891973890751:ios:fbbcf3c952d932d9e10c0a',
    messagingSenderId: '891973890751',
    projectId: 'ploff-kebab-2717e',
    storageBucket: 'ploff-kebab-2717e.appspot.com',
    iosBundleId: 'com.example.ploffKebab.RunnerTests',
  );
}
